### PR TITLE
feat: added error handling for status 404

### PR DESCRIPTION
**Pull request by drkfmorton**
Signed-off-by: Kyle Morton <kylex.f.morton@intel.com>

If your build fails due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/go-mod-secrets/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [x] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

**Review by bnevis-i — DISMISSED** [review]

**Comment by bnevis-i** [comment]
@drkfmorton Please fix linter error.


[2022-08-24T17:37:28.375Z] internal/pkg/vault/secrets_test.go:49:2: `testPathNotFound` is unused (deadcode)

Suggest installing golangci-lint on your path so that linting can be done before checkin.

**Review by lenny-intel — DISMISSED** [review]
LGTM

**Comment by lenny-intel** [comment]
@drkfmorton , you have a linter error. Please run the linter 'make lint' . If you don't have it installed it will tell you how to install it.

For CI Pipeline
```
[2022-08-24T17:37:28.375Z] level=warning msg="[linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."

[2022-08-24T17:37:28.375Z] internal/pkg/vault/secrets_test.go:49:2: `testPathNotFound` is unused (deadcode)

[2022-08-24T17:37:28.375Z] 	testPathNotFound = "/path"

[2022-08-24T17:37:28.375Z] 	^

```

**Review by lenny-intel — APPROVED** [review]
LGTM

**Review by bnevis-i — APPROVED** [review]

**Pull request merged**
