### PR TITLE
Add minimum supported Go version 1.12 to go.mod.

### LINKED ISSUE #30: Add minimum supported Go version to go.mod
Locally, I've upgraded to Go 1.13 to test it out. The project hasn't officially rev'ed to that version yet. One of the things I notice is that when I do a `make test` on a module, an entry indicating go 1.13 as the minimum supported version is put into the go.mod. According to the following article, we should have started seeing this behavior with Go 1.12, but I don't recall that being the case

https://golang.org/doc/go1.12#modules

I wouldn't want this to be checked in as go 1.13 until the project moves to that version. I've tested compilation of the edgex-go services locally with the version directive set to go 1.12 and everything works as far as I can tell. Again, this directive is only indicating a minimum supported version.

I think we should do this fairly soon as we could easily get contributions from people who've upgraded to Go 1.13 and who might miss this small edit.

### PR DESCRIPTION
**Pull request by akramtexas**
Fix #30 

Locally, I upgraded to Go `1.12`, and tested it out via `Makefile`.

### CODE REVIEW

**Comment by akramtexas** [comment]
Recheck

**Comment by akramtexas** [comment]
@lranjbar I'm seeing that error (which we had run into a few days ago) now showing up again in [the log of the failed build check](https://jenkins.edgexfoundry.org/blue/rest/organizations/jenkins/pipelines/edgexfoundry/pipelines/go-mod-secrets/branches/PR-41/runs/3/log/?start=0):
```
ERROR: Project Settings File id (settingsFile) is required for the docker login script.
Finished: FAILURE
```

**Comment by lranjbar** [comment]
The old verify pipeline has been removed now to stop the double builds. Need to rebase off the master branch and push.

**Comment by akramtexas** [comment]
> The old verify pipeline has been removed now to stop the double builds. Need to rebase off the master branch and push.

@lranjbar I will do so, ASAP, thanks 👍

**Comment by akramtexas** [comment]
Rebased.

**Comment by akramtexas** [comment]
Recheck

**Comment by akramtexas** [comment]
Recheck

**Comment by akramtexas** [comment]
Recheck

**Comment by akramtexas** [comment]
> The old verify pipeline has been removed now to stop the double builds. Need to rebase off the master branch and push.

@lranjbar Thanks again for following up. My other three `PR`s have their build checks all passing now. Only this build check remains, and still keeps failing... With the error message logged for [go-mod-secrets-verify-pipeline](https://jenkins.edgexfoundry.org/job/go-mod-secrets-verify-pipeline/44/):
```
HTTP ERROR 404
Problem accessing /job/go-mod-secrets-verify-pipeline/44/. Reason:

    Not Found
Powered by Jetty:// 9.4.z-SNAPSHOT
```

**Comment by lranjbar** [comment]
@akramtexas Right this because the job is removed and won't update noq. However, you should still be able to merge with an approving review since the LF has removed the verify-pipeline from the required statuses.

**Comment by akramtexas** [comment]
> @akramtexas Right this because the job is removed and won't update noq. However, you should still be able to merge with an approving review since the LF has removed the verify-pipeline from the required statuses.

@lranjbar Sounds great, thank you 👍  I am updating my reviewers @michaelestrin ✅

**Pull request merged**
