### PR TITLE
docs: Add badges to readme

### PR DESCRIPTION
**Pull request by soda480**
Add relevant badges to readme

### CODE REVIEW

**Comment by bnevis-i** [comment]
License link is included twice in README.  Go version link doesn't go anywhere useful.

**Review by cjoyv — APPROVED** [review]
👍

**Review by ernestojeda — DISMISSED** [review]
LGTM

**Review by bill-mahoney — DISMISSED** [review]

**Review by cjoyv — APPROVED** [review]
👍

**Pull request merged**
